import {
  ArrowCounterClockwise,
  ArrowFatDown,
  ArrowsLeftRight,
  Binoculars,
  Broadcast,
  Cards,
  Wall,
  DiceFive,
  EyeSlash,
  Feather,
  FlagBanner,
  Flask,
  HandPalm,
  Lightning,
  Lock,
  MagnifyingGlass,
  MapTrifold,
  Megaphone,
  Rows,
  ShieldCheck,
  Shovel,
  Timer,
  Triangle,
  Warning,
  type Icon,
} from '@phosphor-icons/react';

/** Card glyphs referenced by name from card definitions. One icon family, no hand-rolled SVGs. */
const GLYPHS: Record<string, Icon> = {
  ArrowCounterClockwise,
  ArrowFatDown,
  ArrowsLeftRight,
  Binoculars,
  Broadcast,
  Wall,
  DiceFive,
  EyeSlash,
  Feather,
  FlagBanner,
  Flask,
  HandPalm,
  Lightning,
  Lock,
  MagnifyingGlass,
  MapTrifold,
  Megaphone,
  Rows,
  ShieldCheck,
  Shovel,
  Timer,
  Triangle,
  Warning,
};

export const glyphFor = (name: string): Icon => GLYPHS[name] ?? Cards;
