export const ERROR_CODES = [
  'BAD_PAYLOAD',
  'NOT_AUTHED',
  'ROOM_NOT_FOUND',
  'ROOM_FULL',
  'NAME_TAKEN',
  'NOT_HOST',
  'WRONG_STATUS',
  'INVALID_COMPOSITION',
  'NOT_YOUR_TURN',
  'WRONG_PHASE',
  'WRONG_ROLE',
  'KEY_TAINTED',
  'STALE_STATE',
  'ALREADY_PLAYED',
  'CARD_NOT_IN_HAND',
  'CONDITION_FAILED',
  'TARGET_INVALID',
  'COST_UNPAYABLE',
  'TILE_LOCKED',
  'TILE_REVEALED',
  'INVALID_CLUE',
  'NO_GUESSES_LEFT',
  'SPYMASTER_TAKEN',
  'SPYMASTER_PRESENT',
  'PLAYER_NOT_FOUND',
  'RATE_LIMITED',
  'INTERNAL',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

/** Player-facing copy for each code. Kept here so client and server agree on wording. */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  BAD_PAYLOAD: 'That request was malformed.',
  NOT_AUTHED: 'You are not part of this room.',
  ROOM_NOT_FOUND: 'No room with that code.',
  ROOM_FULL: 'This room is full.',
  NAME_TAKEN: 'Someone in this room already uses that name.',
  NOT_HOST: 'Only the host can do that.',
  WRONG_STATUS: 'That action is not available right now.',
  INVALID_COMPOSITION: 'Each team needs one spymaster and at least one operative.',
  NOT_YOUR_TURN: 'It is not your team’s turn.',
  WRONG_PHASE: 'Not in this phase of the turn.',
  WRONG_ROLE: 'Your role cannot do that.',
  KEY_TAINTED: 'You have seen the key, so you cannot guess or play cards.',
  STALE_STATE: 'Someone acted first. The board has moved on.',
  ALREADY_PLAYED: 'Your team already played a card this turn.',
  CARD_NOT_IN_HAND: 'That card is not in your hand.',
  CONDITION_FAILED: 'This card cannot be played right now.',
  TARGET_INVALID: 'That target is not valid for this card.',
  COST_UNPAYABLE: 'You cannot afford this card’s cost.',
  TILE_LOCKED: 'That word is locked for your team this turn.',
  TILE_REVEALED: 'That word is already revealed.',
  INVALID_CLUE: 'Clues are one word, not on the board, with a number from 0 to 9.',
  NO_GUESSES_LEFT: 'No guesses left this turn.',
  SPYMASTER_TAKEN: 'That team already has a spymaster.',
  SPYMASTER_PRESENT: 'The spymaster is still here.',
  PLAYER_NOT_FOUND: 'That player is not in the room.',
  RATE_LIMITED: 'Slow down a little.',
  INTERNAL: 'Something went wrong on our side.',
};
