import type { CardDefinition } from '../types';

const UNREVEALED_NOT_SHIELDED = { unrevealed: true as const, notShielded: true };

export const BOARD_CARDS: CardDefinition[] = [
  {
    id: 'quarantine',
    name: 'Quarantine',
    category: 'board',
    rarity: 'common',
    description: 'Lock a word. The other team cannot pick it on their next turn.',
    rulesText: 'Choose an unrevealed word not shielded by the opponent. They cannot select it during their next turn. The lock is visible to everyone.',
    targeting: { kind: 'tile', filter: UNREVEALED_NOT_SHIELDED },
    cost: {},
    duration: 'opponent_next_turn',
    conditions: [],
    effects: [{ op: 'LOCK_TILE', forTeam: 'opponent', duration: 'opponent_next_turn' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Lock', animation: 'quarantine', sfx: 'latch' },
    balanceNote: 'Denies one route for one turn but tells the opponent you care about that word.',
  },
  {
    id: 'ward',
    name: 'Ward',
    category: 'board',
    rarity: 'common',
    description: 'Shield a word from the other team’s cards until your next turn ends.',
    rulesText: 'Choose any unrevealed word. Opponent cards cannot target it until the end of your next turn. Your own cards still can.',
    targeting: { kind: 'tile', filter: { unrevealed: true } },
    cost: {},
    duration: 'until_own_next_turn_end',
    conditions: [],
    effects: [{ op: 'SHIELD_TILE', duration: 'until_own_next_turn_end' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'ShieldCheck', animation: 'ward', sfx: 'thud' },
    balanceNote: 'Pure counterplay, also a bluff. Leaks that you value the word.',
  },
  {
    id: 'dredge',
    name: 'Dredge',
    category: 'board',
    rarity: 'common',
    description: 'Reveal one random neutral word to everyone.',
    rulesText: 'A random unrevealed neutral word is revealed for both teams. If none remain, nothing happens and the card is still spent.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'instant',
    conditions: [],
    effects: [{ op: 'REVEAL_TILE', selector: 'random_neutral' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Shovel', animation: 'dredge', sfx: 'gravel' },
    balanceNote: 'Perfectly symmetric information; the only edge is timing.',
  },
  {
    id: 'shuffle_step',
    name: 'Shuffle Step',
    category: 'board',
    rarity: 'uncommon',
    description: 'Swap the positions of two hidden words.',
    rulesText: 'Choose two unrevealed words not shielded by the opponent. They trade places on the grid. Words keep their identities.',
    targeting: { kind: 'two_tiles', filter: UNREVEALED_NOT_SHIELDED },
    cost: {},
    duration: 'permanent',
    conditions: [],
    effects: [{ op: 'SWAP_TILES' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'ArrowsLeftRight', animation: 'swap', sfx: 'whoosh' },
    balanceNote: 'Disrupts spatial memory and region-based information cards.',
  },
  {
    id: 'blackout',
    name: 'Blackout',
    category: 'board',
    rarity: 'uncommon',
    description: 'Hide a word’s text from the other team’s operatives on their next turn.',
    rulesText: 'Choose an unrevealed word not shielded by the opponent. During their next turn, their operatives see a blank tile. It can still be selected.',
    targeting: { kind: 'tile', filter: UNREVEALED_NOT_SHIELDED },
    cost: {},
    duration: 'opponent_next_turn',
    conditions: [],
    effects: [{ op: 'HIDE_TILE_TEXT', forTeam: 'opponent', duration: 'opponent_next_turn' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'EyeSlash', animation: 'blackout', sfx: 'ink' },
    balanceNote: 'Information denial for one tile, one turn.',
  },
];
