import type { CardDefinition } from '../types';

export const GAMBLE_CARDS: CardDefinition[] = [
  {
    id: 'double_or_nothing',
    name: 'Double or Nothing',
    category: 'gamble',
    rarity: 'rare',
    description: 'Reveal two words at once. Both yours: +1 guess. Otherwise the usual rules apply.',
    rulesText:
      'Choose two unrevealed words your team may select. They are revealed one after the other as guesses. If both are yours, gain one extra guess. A neutral or opponent word ends your turn as normal. The assassin still loses.',
    targeting: { kind: 'two_tiles', filter: { unrevealed: true, notLocked: true } },
    cost: {},
    duration: 'instant',
    conditions: [{ kind: 'min_guesses_remaining', n: 2 }],
    effects: [{ op: 'RESOLVE_GUESSES', bonusIfAllOwn: 1 }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'DiceFive', animation: 'double', sfx: 'drumroll' },
    balanceNote: 'Same risk as two guesses with a small upside; a tension moment.',
  },
  {
    id: 'loudspeaker',
    name: 'Loudspeaker',
    category: 'gamble',
    rarity: 'uncommon',
    description: 'Gain two guesses this turn. The other team draws an extra card next turn.',
    rulesText: 'Adds two guesses this turn (capped at two extra per turn). At the start of the opponent’s next turn they draw one additional card. Not playable on an unlimited clue.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'this_turn',
    conditions: [{ kind: 'clue_not_unlimited' }],
    effects: [
      { op: 'MODIFY_GUESSES', delta: 2, when: 'now' },
      { op: 'DRAW_CARDS', team: 'opponent', n: 1, when: 'next_turn_start' },
    ],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Megaphone', animation: 'loudspeaker', sfx: 'horn' },
    balanceNote: 'Tempo now, resources for them later.',
  },
  {
    id: 'dig',
    name: 'Dig',
    category: 'gamble',
    rarity: 'common',
    description: 'Search your deck for a card of a chosen type, then discard a card from hand.',
    rulesText: 'Choose a category and a card in your hand to discard. The first matching card in your deck joins your hand; the deck is reshuffled. If none matches, you still discard.',
    targeting: { kind: 'hand_card', filter: { notSelf: true } },
    cost: { discard: 1 },
    duration: 'instant',
    conditions: [{ kind: 'hand_size_at_least', n: 2 }],
    effects: [{ op: 'SEARCH_DECK' }, { op: 'DISCARD_FROM_HAND', selector: 'target' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'MagnifyingGlass', animation: 'dig', sfx: 'scrape' },
    balanceNote: 'Card quality for card quantity; public search.',
  },
  {
    id: 'tremor',
    name: 'Tremor',
    category: 'gamble',
    rarity: 'rare',
    description: 'Something shifts on the board. Roll a random event.',
    rulesText: 'One random event: two hidden words swap places, a hidden word is locked for both teams next turn, a random neutral is revealed, or both teams discard a random card.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'instant',
    conditions: [],
    effects: [{ op: 'RANDOM_EVENT', table: 'tremor' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'Lightning', animation: 'tremor', sfx: 'rumble' },
    balanceNote: 'Every outcome is symmetric; never grants hidden information.',
  },
];
