import type { CardDefinition } from '../types';

const UNREVEALED = { unrevealed: true as const, notShielded: true };

export const INFORMATION_CARDS: CardDefinition[] = [
  {
    id: 'litmus',
    name: 'Litmus',
    category: 'information',
    rarity: 'common',
    description: 'Choose a word. Your team learns whether it is one of yours.',
    rulesText:
      'Costs 1 guess. Choose an unrevealed word not shielded by the opponent. Your team privately learns YES or NO. Everyone sees which word you tested.',
    targeting: { kind: 'tile', filter: UNREVEALED },
    cost: { guesses: 1 },
    duration: 'instant',
    conditions: [{ kind: 'min_guesses_remaining', n: 2 }],
    effects: [{ op: 'PEEK_TILE', mode: 'is_own' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Flask', animation: 'litmus', sfx: 'chime' },
    balanceNote: 'Converts one guess into certainty about one tile; the tested tile is public.',
  },
  {
    id: 'triangulate',
    name: 'Triangulate',
    category: 'information',
    rarity: 'uncommon',
    description: 'Three hidden words are shown. Your team learns which one is yours.',
    rulesText:
      'Costs 1 guess. The server picks three unrevealed words, at least one yours, and privately tells your team one that belongs to you. Everyone sees the three words.',
    targeting: { kind: 'none' },
    cost: { guesses: 1 },
    duration: 'instant',
    conditions: [
      { kind: 'min_guesses_remaining', n: 2 },
      { kind: 'min_own_words_remaining', n: 2 },
    ],
    effects: [{ op: 'PEEK_ONE_OWN_OF_SUBSET', subsetSize: 3 }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Triangle', animation: 'triangulate', sfx: 'chime' },
    balanceNote: 'A guaranteed safe word for a guess; the subset leaks where you got help.',
  },
  {
    id: 'sonar',
    name: 'Sonar',
    category: 'information',
    rarity: 'common',
    description: 'Choose a word. Learn how many of its neighbours are yours: 0, 1, or 2+.',
    rulesText:
      'Choose any unrevealed word. Your team privately learns how many of its up-and-down or side-to-side neighbours are your words, bucketed as 0, 1, or 2+. Everyone sees the ping.',
    targeting: { kind: 'tile', filter: { unrevealed: true } },
    cost: {},
    duration: 'instant',
    conditions: [],
    effects: [{ op: 'PEEK_REGION_COUNT', region: 'neighbors4', buckets: '0_1_2plus' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Broadcast', animation: 'sonar', sfx: 'ping' },
    balanceNote: 'Free but fuzzy; strongest at edges. The ping location is public.',
  },
  {
    id: 'parity',
    name: 'Parity',
    category: 'information',
    rarity: 'common',
    description: 'Choose a row. Learn whether your hidden words in it number odd or even.',
    rulesText: 'Choose a row with at least two hidden words. Your team privately learns ODD or EVEN. Everyone sees the row.',
    targeting: { kind: 'row' },
    cost: {},
    duration: 'instant',
    conditions: [],
    effects: [{ op: 'PEEK_REGION_COUNT', region: 'row', buckets: 'parity' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'Rows', animation: 'parity', sfx: 'tick' },
    balanceNote: 'One bit of information; pairs with Sonar.',
  },
  {
    id: 'cartographer',
    name: 'Cartographer',
    category: 'information',
    rarity: 'uncommon',
    description: 'Choose a 2x2 block. Learn exactly how many of its words are yours.',
    rulesText: 'Costs 1 guess. Choose a 2x2 block (anchor top-left). Your team privately learns the exact count. Everyone sees the block.',
    targeting: { kind: 'block2x2' },
    cost: { guesses: 1 },
    duration: 'instant',
    conditions: [{ kind: 'min_guesses_remaining', n: 2 }],
    effects: [{ op: 'PEEK_REGION_COUNT', region: 'block2x2', buckets: 'exact' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'MapTrifold', animation: 'cartographer', sfx: 'paper' },
    balanceNote: 'Exact count over four tiles for a guess.',
  },
  {
    id: 'hazard_sense',
    name: 'Hazard Sense',
    category: 'information',
    rarity: 'rare',
    description: 'Choose a word. Learn SAFE (yours or neutral) or DANGER (theirs or the assassin).',
    rulesText:
      'Costs 1 guess. Once per game per team. Choose an unrevealed word. Your team privately learns SAFE or DANGER. It never says which kind of danger.',
    targeting: { kind: 'tile', filter: UNREVEALED },
    cost: { guesses: 1 },
    duration: 'instant',
    conditions: [{ kind: 'min_guesses_remaining', n: 2 }, { kind: 'once_per_game_per_team' }],
    effects: [{ op: 'PEEK_TILE', mode: 'safe_or_danger' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'Warning', animation: 'hazard', sfx: 'creak' },
    balanceNote: 'The only assassin-adjacent information; cannot single out the assassin; once per game.',
  },
];
