import type { CardDefinition } from '../types';

export const TEAM_CARDS: CardDefinition[] = [
  {
    id: 'relay',
    name: 'Relay',
    category: 'team',
    rarity: 'common',
    description: 'Your team’s next turn starts with one extra guess.',
    rulesText: 'At the start of your team’s next turn, one extra guess is added to the clue. Extra guesses are capped at two per turn.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'own_next_turn',
    conditions: [],
    effects: [{ op: 'MODIFY_GUESSES', delta: 1, when: 'own_next_turn' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'FlagBanner', animation: 'relay', sfx: 'ratchet' },
    balanceNote: 'Delayed Overtime; rewards planning.',
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    category: 'team',
    rarity: 'uncommon',
    description: 'Until your next turn ends, your hidden words are immune to opponent cards.',
    rulesText: 'Opponent cards cannot target any of your team’s unrevealed words until the end of your next turn. Guessing is unaffected.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'until_own_next_turn_end',
    conditions: [],
    effects: [{ op: 'TEAM_IMMUNITY', duration: 'until_own_next_turn_end' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'Wall', animation: 'bulwark', sfx: 'cloth' },
    balanceNote: 'Blanket Ward; opponents know their board cards are dead for a turn.',
  },
  {
    id: 'salvage',
    name: 'Salvage',
    category: 'team',
    rarity: 'common',
    description: 'Return the top card of your discard pile to your hand.',
    rulesText: 'The most recently discarded card of your team returns to your hand. Needs a non-empty discard pile and room in hand.',
    targeting: { kind: 'discard_top' },
    cost: {},
    duration: 'instant',
    conditions: [{ kind: 'discard_not_empty' }, { kind: 'hand_not_full' }],
    effects: [{ op: 'RECOVER_DISCARD', n: 1 }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'ArrowCounterClockwise', animation: 'salvage', sfx: 'splash' },
    balanceNote: 'Card advantage without information.',
  },
  {
    id: 'foresight',
    name: 'Foresight',
    category: 'team',
    rarity: 'uncommon',
    description: 'At the start of your next turn, draw two cards instead of one.',
    rulesText: 'Your team draws one additional card at the start of its next turn. Hand size limits still apply.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'own_next_turn',
    conditions: [],
    effects: [{ op: 'DRAW_CARDS', team: 'own', n: 1, when: 'next_turn_start' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'Binoculars', animation: 'foresight', sfx: 'slide' },
    balanceNote: 'Card advantage only; one play per turn keeps it from adding effects.',
  },
];
