import type { CardDefinition } from '../types';

export const TURN_CARDS: CardDefinition[] = [
  {
    id: 'overtime',
    name: 'Overtime',
    category: 'turn',
    rarity: 'common',
    description: 'Gain one extra guess this turn.',
    rulesText: 'Adds one guess to this turn. Extra guesses from all sources are capped at two per turn. Not playable on an unlimited clue.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'this_turn',
    conditions: [{ kind: 'clue_not_unlimited' }],
    effects: [{ op: 'MODIFY_GUESSES', delta: 1, when: 'now' }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Timer', animation: 'overtime', sfx: 'tick' },
    balanceNote: 'Baseline tempo card; still needs a correct guess to matter.',
  },
  {
    id: 'second_chance',
    name: 'Second Chance',
    category: 'turn',
    rarity: 'uncommon',
    description: 'Your next wrong guess this turn does not end your turn.',
    rulesText: 'If your team next reveals a neutral or opponent word this turn, the word is still revealed but your turn continues. Never protects against the assassin.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'this_turn',
    conditions: [{ kind: 'no_forgive_active' }],
    effects: [{ op: 'FORGIVE_WRONG_GUESS', count: 1 }],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'Feather', animation: 'second_chance', sfx: 'chime' },
    balanceNote: 'Reduces variance on a bold turn; the wrong word still leaks information.',
  },
  {
    id: 'abstain',
    name: 'Abstain',
    category: 'turn',
    rarity: 'common',
    description: 'End your turn now. Your next turn starts with one extra guess.',
    rulesText: 'Ends your turn immediately. At the start of your team’s next turn, one extra guess is added to the clue.',
    targeting: { kind: 'none' },
    cost: { endsTurn: true },
    duration: 'own_next_turn',
    conditions: [],
    effects: [
      { op: 'MODIFY_GUESSES', delta: 1, when: 'own_next_turn' },
      { op: 'END_TURN' },
    ],
    cooldownTurns: 0,
    pools: ['mvp', 'full'],
    presentation: { glyph: 'HandPalm', animation: 'abstain', sfx: 'soft' },
    balanceNote: 'The classic "do not risk it" made explicit, with a small reward.',
  },
  {
    id: 'pressure',
    name: 'Pressure',
    category: 'turn',
    rarity: 'uncommon',
    description: 'The other team has one fewer guess on their next turn.',
    rulesText: 'On the opponent’s next turn, their guess allowance is reduced by one, to a minimum of one. Visible to everyone before they clue.',
    targeting: { kind: 'none' },
    cost: {},
    duration: 'opponent_next_turn',
    conditions: [],
    effects: [{ op: 'MODIFY_GUESSES', delta: -1, when: 'opponent_next_turn' }],
    cooldownTurns: 0,
    pools: ['full'],
    presentation: { glyph: 'ArrowFatDown', animation: 'pressure', sfx: 'drain' },
    balanceNote: 'Tempo only; a good spymaster adapts the clue.',
  },
];
